exclude: docs/
repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: detect-aws-credentials
        args: [ '--allow-missing-credentials' ]
  - repo: git@github.com:golangci/golangci-lint.git
    rev: v1.56.1
    hooks:
      - id: golangci-lint
  - repo: git@github.com:TekWizely/pre-commit-golang.git
    rev: v1.0.0-rc.1
    hooks:
      - id: go-imports
  - repo: local
    hooks:
      - id: generate-mocks
        name: generate-mocks
        entry: bash -c 'make generate'
        language: system
        types: [ bash ]
        pass_filenames: false
        always_run: true
