name: go-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GOPRIVATE: github.com/honestbank
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  go-tests:
    name: go-tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test and generate code coverage on main module
        run: make test

      - name: Test and generate code coverage on extensions/cloudevents
        run: |
          cd extensions/cloudevents
          make test
      - run: tail -n +2 extensions/cloudevents/cover.out >> cover.out && rm extensions/cloudevents/cover.out

      - name: Test and generate code coverage on extensions/google-cloud
        run: |
          cd extensions/google-cloud
          make test
      - run: tail -n +2 extensions/google-cloud/cover.out >> cover.out && rm extensions/google-cloud/cover.out

      - name: Go lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m --modules-download-mode=readonly
          skip-pkg-cache: true
          skip-build-cache: true

      - name: SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  release:
    name: semantic-release
    runs-on: ubuntu-latest
    needs: [go-tests]
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
        id: go

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 19
          extra_plugins: |
            @semantic-release/git@10.0.1
            @semantic-release/exec@6.0.2
            @semantic-release/changelog@6.0.1
