name: go-tests

on: [workflow_call]

jobs:
  build:
    name: go-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ "1.20" ]
    steps:
      - name: set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: generate mocks
        run: make generate

      - name: setup go modules
        run: go clean -modcache; go mod tidy; go mod download; go mod verify

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m --modules-download-mode=readonly
          skip-pkg-cache: true
          skip-build-cache: true

      - name: test and generate code coverage
        run: go test -v -race -coverprofile=./cover.out -covermode=atomic ./...

      - name: sonarcloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        continue-on-error: true
