name: go-tests

on: [workflow_call]

jobs:
  build:
    name: go-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ "1.18" ]
    steps:
      - name: set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: generate mocks
        run: make generate

      - name: setup go modules
        run: go clean -modcache; go mod tidy; go mod download; go mod verify

      - name: install golangci-lint
        # Install golangci-lint from source instead of using
        # golangci-lint-action to ensure the golangci-lint binary is built with
        # the same Go version we're targeting.
        # Avoids incompatibility issues such as:
        # - https://github.com/golangci/golangci-lint/issues/2922
        # - https://github.com/golangci/golangci-lint/issues/2673
        # - https://github.com/golangci/golangci-lint-action/issues/442
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2
      - name: run golangci-lint
        run: golangci-lint run --version --verbose --out-format=github-actions

      - name: test and generate code coverage
        run: go test -v -race -coverprofile=./cover.out -covermode=atomic ./...

      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: cover.out
          local-prefix: github.com/lukecold/event-driver
          threshold-file: 80
          threshold-package: 80
          threshold-total: 80
