name: deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  tests:
    uses: ./.github/workflows/go-tests.yaml
    secrets: inherit

  deploy:
    needs: [ tests ]
    uses: ./.github/workflows/release.yaml
    secrets: inherit
