name: pull-requests

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

permissions:
  pull-requests: read

jobs:
  tests:
    uses: ./.github/workflows/go-tests.yaml
    secrets: inherit

  semantic-pr:
    uses: ./.github/workflows/semantic-pr.yaml
    secrets: inherit
