name: semantic-pr

on: [workflow_call]

permissions:
  pull-requests: read

jobs:
  main:
    name: validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
